STARTING_PORT = 10000
CHARACTERS = ['marth',
              'fox',
              'falco',
              'falcon',
              'sheik',
              'samus',
              'yoshi',
              'pikachu',
              'ics',
              'dk',
              'gaw',
              'kirby',
              'bowser',
              'link',
              'luigi',
              'mario',
              'mewtwo',
              'ness',
              'ylink',
              'doc',
              'roy',
              'pichu',
              'ganon',
              'puff',
              'peach']
TOTAL_NUM_PORTS = 10